import {
  AppstoreOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  CalendarOutlined,
  CloudOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  EnvironmentOutlined,
  FileTextOutlined,
  FlagOutlined,
  FolderOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartOutlined,
  HomeOutlined,
  KeyOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  ProfileOutlined,
  RocketOutlined,
  SafetyOutlined,
  SettingOutlined,
  ShoppingOutlined,
  StarOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  UserOutlined,
} from '@ant-design/icons'

/**
 * 系统菜单图标映射表（图标选择器与侧边栏共用）
 * key 为存入后端 icon 字段的标识，value 为对应 AntD 图标组件
 */
export const MENU_ICONS = {
  setting: SettingOutlined,
  user: UserOutlined,
  team: TeamOutlined,
  menu: MenuOutlined,
  appstore: AppstoreOutlined,
  book: BookOutlined,
  database: DatabaseOutlined,
  folder: FolderOutlined,
  dashboard: DashboardOutlined,
  'file-text': FileTextOutlined,
  profile: ProfileOutlined,
  safety: SafetyOutlined,
  home: HomeOutlined,
  shopping: ShoppingOutlined,
  calendar: CalendarOutlined,
  bell: BellOutlined,
  star: StarOutlined,
  tool: ToolOutlined,
  cloud: CloudOutlined,
  global: GlobalOutlined,
  picture: PictureOutlined,
  tags: TagsOutlined,
  'bar-chart': BarChartOutlined,
  'pie-chart': PieChartOutlined,
  gift: GiftOutlined,
  rocket: RocketOutlined,
  thunderbolt: ThunderboltOutlined,
  heart: HeartOutlined,
  flag: FlagOutlined,
  key: KeyOutlined,
  lock: LockOutlined,
  mail: MailOutlined,
  phone: PhoneOutlined,
  environment: EnvironmentOutlined,
}

/** 图标名称列表（选择器网格渲染用） */
export const ICON_NAMES = Object.keys(MENU_ICONS)
